language: python
python:
  - 3.3
  - 3.4
  - 3.6
install:
  - pip install -q errbot pytest pytest-pep8 --use-wheel
  - pip install -q coverage coveralls --use-wheel
  - test -f requirements.txt && pip install -r requirements.txt
script:
  - coverage run --source . -m py.test --pep8 -v
after_success:
  - coveralls
notifications:
  email : false
